name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"  # 使用官方稳定版
          cache: true         # 启用自动模块缓存

      - name: Verify Go
        run: |
          go version
          echo "GOROOT=$GOROOT"  # 确认环境变量

      - name: Build with build.sh
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-binaries
          path: build/
          retention-days: 3